version: "3.9"

services:

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    command: redis-server

  flower: #Контейнер для мониторинга очереди задач (если не требуется, то можно его удалить)
    image: mher/flower:master
    container_name: flower
    restart: unless-stopped
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0 
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      FLOWER_PORT: 5555
    ports:
      - 5555:5555
    depends_on:
      - redis

  celery:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: celery
    environment:
      REDIS_HOST: redis # хост Redis
      REDIS_PORT: 6379 # порт Redis
    depends_on:
      - redis

